version: '3.8'

services:
  php-fpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www
    expose:
      - "9000"

  nginx:
    image: nginx:alpine
    depends_on:
      - php-fpm
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
